env: standard
runtime: nodejs10
service: default
manual_scaling:
  instances: 1

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|png))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|png)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
